name: flutter_localization
description: Localization support library for flutter application
version: 0.0.1
author: Yuriy Bereguliak <ybereguliak95@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization fo application
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
